[package]
name = "goool"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
term_size = "0.3.2"


[profile.release]
strip = true
opt-level = "s"
lto = "thin"
codegen-units = 1


[profile.dev]
opt-level = 1